[package]
name = "RapBattle"
version = "1.0.0"

[addresses]
battle_addr = "_"
minter_addr = "_"
# This is the official address for the Aptos Digital Asset (NFT) modules.
aptos_token_v2 = "0x4"

[dev-addresses]
battle_addr = "0x42"
minter_addr = "0x100"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }

# THIS IS THE CRITICAL MISSING DEPENDENCY
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects", rev = "mainnet" }

[dev-dependencies]